name = "Permanents"
uuid = "e0809bc7-674c-4283-bd35-3a6d484c6d12"
authors = ["Beno√Æt Seron <benoitseron@gmail.com> and Antoine Restivo <antoinerestivo@hotmail.fr>"]
version = "0.2.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
BosonSampling = "4f11539d-f4e6-47f3-a15e-0809978c3ed1"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ArgCheck = "2"
Combinatorics = "1"
Distributions = "0.25"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
