name = "Permanents"
uuid = "e0809bc7-674c-4283-bd35-3a6d484c6d12"
authors = ["Beno√Æt Seron <benoitseron@gmail.com> and Antoine Restivo <antoinerestivo@hotmail.fr>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Combinatorics = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
